apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic-1
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 2
  
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic-2
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 2
